centos6:
    extends:
        file: base.yml
        service: build
    build: centos6/
    environment:
        - BOOST_ROOT=/usr/local/boost157
        - CXXFLAGS=-I/usr/local/boost157/include
        - LDFLAGS=-L/usr/local/boost157/lib

centos7:
    extends:
        file: base.yml
        service: build
    build: centos7/

ubuntu1504:
    extends:
        file: base.yml
        service: build
    build: ubuntu1504/

ubuntu1510:
    extends:
        file: base.yml
        service: build
    build: ubuntu1510/

ubuntu1510sb:
    extends:
        file: base.yml
        service: build
    build: ubuntu1510sb/
    command: /tools/build.sh -Dbioformats-superbuild=ON

wheezygcc493:
    extends:
        file: base.yml
        service: build
    build: wheezygcc493/
